<?php
/** Capability-protected aggregate analytics workspace. @package SiteMaster */
namespace Abhinava\SiteMaster\Analytics;
defined( 'ABSPATH' ) || exit;
final class AnalyticsAdmin {
	private string $profile;
	public function __construct(string $profile){$this->profile=$profile;}
	public static function capability():string{return (string)apply_filters('site_master_analytics_capability','edit_others_posts');}
	public function register():void{add_action('admin_menu',array($this,'menu'));add_action('admin_post_site_master_analytics_settings',array($this,'save'));add_action('admin_post_site_master_analytics_csv',array($this,'csv'));add_action('add_meta_boxes_post',array($this,'meta_box'));}
	public function menu():void{add_submenu_page('site-master',__('Analytics','site-master'),__('Analytics','site-master'),self::capability(),'site-master-analytics',array($this,'render'));}
	public function meta_box():void{add_meta_box('site-master-analytics',__('Site Master Analytics','site-master'),array($this,'render_meta'),'post','side','default');}
	public function render_meta(\WP_Post $post):void{if(!current_user_can('edit_post',$post->ID))return;$r=new Reporting($this->profile);$x=$r->lifetime($post->ID);echo '<p>'.esc_html(sprintf(__('Lifetime: %1$d (legacy %2$d + measured %3$d)','site-master'),$x['lifetime'],$x['baseline'],$x['measured'])).'</p>';echo '<p>'.esc_html(sprintf(__('Today: %1$d · 7d: %2$d · 30d: %3$d','site-master'),$r->post_views($post->ID,1),$r->post_views($post->ID,7),$r->post_views($post->ID,30))).'</p>';$peak=$r->peak_hour($post->ID);echo'<p>'.esc_html(sprintf(__('First hour: %1$s · First 24h: %2$s · Peak: %3$s','site-master'),$r->launch_status($post->ID,HOUR_IN_SECONDS),$r->launch_status($post->ID,DAY_IN_SECONDS),$peak?($peak['bucket_utc'].' / '.$peak['views']):__('Unavailable','site-master'))).'</p>';echo '<p><a href="'.esc_url(admin_url('admin.php?page=site-master-analytics&tab=content&post_id='.$post->ID)).'">'.esc_html__('Open analytics','site-master').'</a></p>';}
	public function render():void{
		if(!current_user_can(self::capability()))return;$tabs=array('overview','content','realtime','authors','taxonomies','acquisition','settings');$tab=isset($_GET['tab'])?sanitize_key(wp_unslash($_GET['tab'])):'overview';if(!in_array($tab,$tabs,true))$tab='overview';
		echo '<div class="wrap"><h1>'.esc_html__('Site Master Analytics','site-master').'</h1><nav class="nav-tab-wrapper">';foreach($tabs as $item){echo '<a class="nav-tab '.($tab===$item?'nav-tab-active':'').'" href="'.esc_url(admin_url('admin.php?page=site-master-analytics&tab='.$item)).'">'.esc_html(ucfirst($item)).'</a>';}echo '</nav>';
		if(!Config::enabled($this->profile))echo '<div class="notice notice-info"><p>'.esc_html__('Tracking is disabled for this profile. Existing aggregate reports remain available.','site-master').'</p></div>';if('techgenyz'===$this->profile&&function_exists('tgm_increment_post_views_count'))echo'<div class="notice notice-warning"><p>'.esc_html__('A legacy Techgenyz view tracker appears active. Disable its persistent counter before treating the Site Master cutover as authoritative.','site-master').'</p></div>';
		if('settings'===$tab){$this->settings();echo'</div>';return;}
		$r=new Reporting($this->profile);$today=wp_date('Y-m-d',null,wp_timezone());$start=wp_date('Y-m-d',strtotime('-6 days'),wp_timezone());echo '<h2>'.esc_html(ucfirst($tab)).'</h2>';
		if('realtime'===$tab){foreach(array(5,30,60)as$m){$v=$r->realtime($m);echo '<p>'.esc_html("{$m}m: {$v['views']} views / {$v['readers']} estimated readers").'</p>';}}
		elseif('overview'===$tab){foreach(array(1,7,30,90)as$days){$now=$r->window($days);$prior=$r->window($days,$days);$change=Reporting::percent_change($now['views'],$prior['views']);echo'<p>'.esc_html(sprintf(__('%1$dd: %2$d views, %3$d estimated daily readers, %4$d viewed posts, change %5$s','site-master'),$days,$now['views'],$now['readers'],$now['posts'],null===$change?'—':$change.'%')).'</p>';}$y=$r->window(1,1);echo'<p>'.esc_html(sprintf(__('Yesterday: %d views','site-master'),$y['views'])).'</p><h3>'.esc_html__('Top content','site-master').'</h3>';$this->rows($r->top($start,$today,10));echo'<h3>'.esc_html__('Trending content','site-master').'</h3>';$this->rows($r->trending(10));}
		else{$views=$r->views($start,$today);echo '<p>'.esc_html(sprintf(__('Measured views in the last 7 days: %d','site-master'),$views)).'</p>';$types='authors'===$tab?array('author'):( 'taxonomies'===$tab?array('category','tag'):( 'acquisition'===$tab?array('referrer','utm_source','utm_medium','utm_campaign','device','country'):array()));foreach($types as$type){echo'<h3>'.esc_html(ucwords(str_replace('_',' ',$type))).'</h3><table class="widefat striped"><thead><tr><th>'.esc_html__('Value','site-master').'</th><th>'.esc_html__('Views','site-master').'</th></tr></thead><tbody>';foreach($r->dimensions($type,$start,$today)as$row)echo'<tr><td>'.esc_html($row['dimension_value']).'</td><td>'.esc_html($row['views']).'</td></tr>';echo'</tbody></table>';}echo '<p>'.esc_html__('Reports use aggregate data; empty sections mean no measured data is available yet.','site-master').'</p>';}
		echo '<p><a class="button" href="'.esc_url(wp_nonce_url(admin_url('admin-post.php?action=site_master_analytics_csv&start='.$start.'&end='.$today),'site_master_analytics_csv')).'">'.esc_html__('Export aggregate CSV','site-master').'</a></p></div>';
	}
	private function settings():void{if(!current_user_can('manage_options')){echo'<p>'.esc_html__('Administrator access is required.','site-master').'</p>';return;}$s=Config::get($this->profile);echo'<form method="post" action="'.esc_url(admin_url('admin-post.php')).'"><input type="hidden" name="action" value="site_master_analytics_settings">';wp_nonce_field('site_master_analytics_settings');echo'<label><input type="checkbox" name="enabled" value="1" '.checked($s['enabled'],true,false).' '.disabled($this->profile,'unconfigured',false).'> '.esc_html__('Enable analytics','site-master').'</label><br><label><input type="checkbox" name="exclude_logged_in" value="1" '.checked($s['exclude_logged_in'],true,false).'> '.esc_html__('Exclude logged-in readers','site-master').'</label><p><label>'.esc_html__('Raw retention hours (48–168)','site-master').' <input type="number" min="48" max="168" name="raw_retention_hours" value="'.esc_attr($s['raw_retention_hours']).'"></label></p><p><label>'.esc_html__('Trusted country header','site-master').' <input name="trusted_country_header" value="'.esc_attr($s['trusted_country_header']).'"></label></p>';submit_button();echo'</form>';}
	private function rows(array $rows):void{echo'<table class="widefat striped"><thead><tr><th>'.esc_html__('Post','site-master').'</th><th>'.esc_html__('Views / score','site-master').'</th></tr></thead><tbody>';foreach($rows as$row){echo'<tr><td>'.esc_html(get_the_title((int)$row['post_id'])).'</td><td>'.esc_html($row['views']??$row['score']??0).'</td></tr>';}echo'</tbody></table>';}
	public function save():void{if(!current_user_can('manage_options'))wp_die(esc_html__('Not allowed.','site-master'));check_admin_referer('site_master_analytics_settings');if('unconfigured'===$this->profile)wp_die(esc_html__('Configure a supported profile first.','site-master'));$all=get_option(Config::OPTION,array());$all=is_array($all)?$all:array();$all[$this->profile]=array('enabled'=>isset($_POST['enabled']),'exclude_logged_in'=>isset($_POST['exclude_logged_in']),'raw_retention_hours'=>max(48,min(168,absint($_POST['raw_retention_hours']??72))),'trusted_country_header'=>preg_replace('/[^A-Z0-9_-]/','',strtoupper(sanitize_text_field(wp_unslash($_POST['trusted_country_header']??'')))));update_option(Config::OPTION,$all,false);wp_safe_redirect(admin_url('admin.php?page=site-master-analytics&tab=settings&updated=1'));exit;}
	public function csv():void{if(!current_user_can(self::capability()))wp_die(esc_html__('Not allowed.','site-master'));check_admin_referer('site_master_analytics_csv');$end=sanitize_text_field(wp_unslash($_GET['end']??''));$start=sanitize_text_field(wp_unslash($_GET['start']??''));if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$start)||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$end)||strtotime($end)<strtotime($start)||strtotime($end)-strtotime($start)>366*DAY_IN_SECONDS)wp_die(esc_html__('Invalid date range.','site-master'));$rows=(new Reporting($this->profile))->top($start,$end,100);$ids=array_map('absint',wp_list_pluck($rows,'post_id'));if($ids)_prime_post_caches($ids,false,false);nocache_headers();header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename=site-master-analytics.csv');$out=fopen('php://output','w');fputcsv($out,array('Post ID','Title','Views'));foreach($rows as$row){$title=get_the_title((int)$row['post_id']);if(preg_match('/^[=+\-@]/',$title))$title="'".$title;fputcsv($out,array((int)$row['post_id'],$title,(int)$row['views']));}fclose($out);exit;}
}
