<?php
/** Bounded aggregate-only reporting query service. @package SiteMaster */
namespace Abhinava\SiteMaster\Analytics;
defined( 'ABSPATH' ) || exit;
final class Reporting {
	private string $profile;
	public function __construct( string $profile ) { $this->profile=$profile; }
	public static function percent_change( int $current, int $previous ): ?float { return 0 === $previous ? ( 0 === $current ? 0.0 : null ) : round((($current-$previous)/$previous)*100,1); }
	public static function trend_score( int $recent, int $previous, int $day_views ): float { return round((($recent+1)/($previous+1))*log10($day_views+1),6); }
	public function lifetime( int $post_id ): array { global $wpdb; $t=Tables::names(); $row=$wpdb->get_row($wpdb->prepare("SELECT COALESCE(b.baseline_count,0) baseline,COALESCE(x.views,0) measured FROM (SELECT %d post_id) p LEFT JOIN {$t['baseline']} b ON b.profile=%s AND b.post_id=p.post_id LEFT JOIN {$t['totals']} x ON x.profile=%s AND x.post_id=p.post_id",$post_id,$this->profile,$this->profile),ARRAY_A); $b=(int)($row['baseline']??0);$m=(int)($row['measured']??0);return array('baseline'=>$b,'measured'=>$m,'lifetime'=>$b+$m); }
	public function views( string $start_day, string $end_day ): int { global $wpdb;$t=Tables::names();return (int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(views),0) FROM {$t['daily']} WHERE profile=%s AND post_id=0 AND report_day BETWEEN %s AND %s",$this->profile,$start_day,$end_day)); }
	public function top( string $start_day, string $end_day, int $limit=20 ): array { global $wpdb;$t=Tables::names();$limit=max(1,min(100,$limit));return $wpdb->get_results($wpdb->prepare("SELECT post_id,SUM(views) views FROM {$t['daily']} WHERE profile=%s AND post_id>0 AND report_day BETWEEN %s AND %s GROUP BY post_id ORDER BY views DESC LIMIT %d",$this->profile,$start_day,$end_day,$limit),ARRAY_A); }
	public function post_views(int $post_id,int $days):int{global$wpdb;$t=Tables::names();$days=max(1,min(366,$days));$end=wp_date('Y-m-d',null,wp_timezone());$start=wp_date('Y-m-d',strtotime('-'.($days-1).' days'),wp_timezone());return(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(views),0) FROM {$t['daily']} WHERE profile=%s AND post_id=%d AND report_day BETWEEN %s AND %s",$this->profile,$post_id,$start,$end));}
	public function peak_hour(int $post_id):array{global$wpdb;$t=Tables::names();$row=$wpdb->get_row($wpdb->prepare("SELECT bucket_utc,views FROM {$t['hourly']} WHERE profile=%s AND post_id=%d ORDER BY views DESC,bucket_utc ASC LIMIT 1",$this->profile,$post_id),ARRAY_A);return is_array($row)?$row:array();}
	public function dimensions(string $type,string $start,string $end,int $limit=50):array{global$wpdb;$t=Tables::names();$allowed=array('author','category','tag','referrer','utm_source','utm_medium','utm_campaign','device','country');if(!in_array($type,$allowed,true))return array();$limit=max(1,min(100,$limit));return$wpdb->get_results($wpdb->prepare("SELECT dimension_value,SUM(views) views FROM {$t['dimensions']} WHERE profile=%s AND dimension_type=%s AND report_day BETWEEN %s AND %s GROUP BY dimension_value ORDER BY views DESC LIMIT %d",$this->profile,$type,$start,$end,$limit),ARRAY_A);}
	public function window(int $days,int $offset=0):array{global$wpdb;$t=Tables::names();$days=max(1,min(366,$days));$offset=max(0,min(366,$offset));$end=wp_date('Y-m-d',strtotime('-'.$offset.' days'),wp_timezone());$start=wp_date('Y-m-d',strtotime('-'.($offset+$days-1).' days'),wp_timezone());$row=$wpdb->get_row($wpdb->prepare("SELECT COALESCE(SUM(views),0) views,COALESCE(SUM(estimated_readers),0) readers FROM {$t['daily']} WHERE profile=%s AND post_id=0 AND report_day BETWEEN %s AND %s",$this->profile,$start,$end),ARRAY_A);$posts=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(DISTINCT post_id) FROM {$t['daily']} WHERE profile=%s AND post_id>0 AND report_day BETWEEN %s AND %s AND views>0",$this->profile,$start,$end));if(0===$offset){$today=wp_date('Y-m-d',null,wp_timezone());$raw=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(DISTINCT reader_hash) FROM {$t['events']} WHERE profile=%s AND report_day=%s",$this->profile,$today));$stored=(int)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(estimated_readers,0) FROM {$t['daily']} WHERE profile=%s AND post_id=0 AND report_day=%s",$this->profile,$today));$row['readers']=(int)($row['readers']??0)-$stored+$raw;}return array('views'=>(int)($row['views']??0),'readers'=>(int)($row['readers']??0),'posts'=>$posts,'start'=>$start,'end'=>$end);}
	public function trending(int $limit=10):array{global$wpdb;$t=Tables::names();$limit=max(1,min(50,$limit));$now=gmdate('Y-m-d H:i:s');$recent=gmdate('Y-m-d H:i:s',time()-HOUR_IN_SECONDS);$previous=gmdate('Y-m-d H:i:s',time()-2*HOUR_IN_SECONDS);$day=gmdate('Y-m-d H:i:s',time()-DAY_IN_SECONDS);$rows=$wpdb->get_results($wpdb->prepare("SELECT post_id,SUM(CASE WHEN occurred_at_utc>=%s THEN 1 ELSE 0 END) recent,SUM(CASE WHEN occurred_at_utc>=%s AND occurred_at_utc<%s THEN 1 ELSE 0 END) previous,COUNT(*) day_views FROM {$t['events']} WHERE profile=%s AND occurred_at_utc>=%s AND occurred_at_utc<=%s GROUP BY post_id ORDER BY recent DESC LIMIT %d",$recent,$previous,$recent,$this->profile,$day,$now,$limit),ARRAY_A);foreach($rows as&$row){$row['score']=self::trend_score((int)$row['recent'],(int)$row['previous'],(int)$row['day_views']);}unset($row);usort($rows,static fn($a,$b)=>$b['score']<=>$a['score']);return$rows;}
	public function realtime( int $minutes ): array { global $wpdb;$t=Tables::names();$minutes=max(1,min(60,$minutes));$since=gmdate('Y-m-d H:i:s',time()-$minutes*MINUTE_IN_SECONDS);$row=$wpdb->get_row($wpdb->prepare("SELECT COUNT(*) views,COUNT(DISTINCT reader_hash) readers FROM {$t['events']} WHERE profile=%s AND occurred_at_utc>=%s",$this->profile,$since),ARRAY_A);return array('views'=>(int)($row['views']??0),'readers'=>(int)($row['readers']??0)); }
	public function launch_status( int $post_id, int $window_seconds ): string { $published=get_post_time('U',true,$post_id);$cut=(new StateRepository())->get($this->profile,'cutover_at_utc');if(!$published||''===$cut)return'unavailable';$cut_ts=strtotime($cut.' UTC');if($published<$cut_ts)return'unavailable';return time()<$published+$window_seconds?'partial':'complete'; }
}
