<?php
/** Techgenyz editorial terms adapter. @package SiteMaster */
namespace Abhinava\SiteMaster\Elementor\Compatibility\Techgenyz;
defined('ABSPATH')||exit;
final class PostTermsWidget extends LegacyWidgetBase {
	public function get_name():string{return'post_terms';} public function get_title():string{return esc_html__('Techgenyz Post Terms','site-master');} public function get_icon():string{return'eicon-tags';}
	public function render_compatibility(?array$s=null,int$post_id=0):string{$s=$s??$this->settings();$post_id=$post_id?:self::post_id();$tax=in_array((string)($s['taxonomy']??'category'),array('category','post_tag'),true)?(string)($s['taxonomy']??'category'):'category';$terms=get_the_terms($post_id,$tax);if(empty($terms)||is_wp_error($terms))return'';$include=array_map('absint',(array)($s['include_terms']??array()));$exclude=array_map('absint',(array)($s['exclude_terms']??array()));$terms=array_values(array_filter($terms,static fn($t)=>!in_array((int)$t->term_id,$exclude,true)&&(empty($include)||in_array((int)$t->term_id,$include,true))));if(self::on($s,'order_by_selection',false)&&$include){$map=array();foreach($terms as$t)$map[(int)$t->term_id]=$t;$terms=array_values(array_filter(array_map(static fn($id)=>$map[$id]??null,$include)));}else{$by=in_array((string)($s['orderby']??'name'),array('name','term_id','count'),true)?(string)($s['orderby']??'name'):'name';$direction='DESC'===(string)($s['order']??'ASC')?-1:1;usort($terms,static fn($a,$b)=>$direction*strnatcasecmp((string)$a->$by,(string)$b->$by));}$link=self::on($s,'link_terms',true);$separator=sanitize_text_field((string)($s['separator']??' '));$items=array();foreach($terms as$t){$name=esc_html($t->name);$items[]='<span class="term-item">'.($link?'<a href="'.esc_url(get_term_link($t)).'">'.$name.'</a>':$name).'</span>';}return $items?'<div class="elementor-post-terms-wrapper"><div class="elementor-post-terms">'.implode(esc_html($separator),$items).'</div></div>':'';}
	protected function render():void{echo$this->render_compatibility();}
}
